version: '3'
services:
  prometheus:
    image: 'prom/prometheus'
    ports:
     - '9090:9090'
    volumes:
     - '${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml:ro'
     - 'prometheus-volume:/prometheus'
  influxdb:
    image: influxdb
    ports:
      - '8086:8086'  # HTTP API
      - '8083:8083'  # Administration interface
      - '2003:2003'  # Graphite
    environment:
      INFLUXDB_GRAPHITE_ENABLED: 'true'
      INFLUXDB_ADMIN_ENABLED: 'true'
      INFLUXDB_DB: influx
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_READ_USER: reader
      INFLUXDB_READ_USER_PASSWORD: reader
    volumes:
      - 'influxdb-volume:/var/lib/influxdb'
  app:
    image: 'prom/client_golang_examples_simple:beorn7_histogram'
    command: '/simple'
  grafana:
    image: 'grafana/grafana'
    volumes: 
      - 'grafana-volume:/var/lib/grafana'
      - '${PWD}/grafana/:/etc/grafana/provisioning/'
    ports:
      - '3000:3000'
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_AUTH_ANONYMOUS_ORG_ROLE: 'admin'
      #GF_AUTH_ANONYMOUS_ORG_NAME: 'Avast'
      GF_USERS_ALLOW_SIGN_UP: 'false'
      GF_USERS_ALLOW_ORG_CREATE: 'false'

volumes:
  grafana-volume:
  prometheus-volume:
  influxdb-volume:
